# Pandas Introduction

In [1]:
import numpy as np
import pandas as pd

## Objects

### Series

In [2]:
# Pandas Series
data = pd.Series([0.25, 0.5, 0.75, 1.0])
display(data)

display(data.values) # numpy array
display(data.index)

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

array([0.25, 0.5 , 0.75, 1.  ])

RangeIndex(start=0, stop=4, step=1)

In [3]:
# Is somehow a Python dictionary, but it is more efficient
data = pd.Series([0.25, 0.5, 0.75, 1.0], index=['a', 'b', 'c', 'd'])
display(data)

data = pd.Series([0.25, 0.5, 0.75, 1.0], index=[2, 5, 3, 7])
display(data)

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

2    0.25
5    0.50
3    0.75
7    1.00
dtype: float64

In [4]:
population_dict = {
    'California': 123456789,
    'Texas': 97654321,
    'New York': 12341234124,
    'Florida': 987987987,
}
population = pd.Series(population_dict)
display(population)

display(population['California':'New York'])

California      123456789
Texas            97654321
New York      12341234124
Florida         987987987
dtype: int64

California      123456789
Texas            97654321
New York      12341234124
dtype: int64

### DataFrame

In [5]:
# We can combine two Series object to make a DataFrame object
display(population)

area = pd.Series({
    'California': 123123,
    'Texas': 98098,
    'Florida': 123456,
    'New York': 98765,
})
display(area)

states = pd.DataFrame({'population': population, 'area': area})
display(states)

display(states.index)
display(states.columns)

California      123456789
Texas            97654321
New York      12341234124
Florida         987987987
dtype: int64

California    123123
Texas          98098
Florida       123456
New York       98765
dtype: int64

             population    area
California    123456789  123123
Florida       987987987  123456
New York    12341234124   98765
Texas          97654321   98098

Index(['California', 'Florida', 'New York', 'Texas'], dtype='object')

Index(['population', 'area'], dtype='object')

In [6]:
# We can think about a DataFrame like a dictionary which maps column name to a Series of column data
display(states['area'])
display(states['population'])

California    123123
Florida       123456
New York       98765
Texas          98098
Name: area, dtype: int64

California      123456789
Florida         987987987
New York      12341234124
Texas            97654321
Name: population, dtype: int64

#### Construction of DataFrame objects

In [7]:
# From a series object
x = pd.DataFrame(population, columns=['population'])
display(x)

# From a list of dicts
x = pd.DataFrame([{'a': i, 'b': 2 * i} for i in range(3)])
display(x)

# If a value is missing pandas will fill up its values with NaN
x = pd.DataFrame([{'a': 1, 'b': 2}, {'a': 3, 'c': 14}])
display(x)

             population
California    123456789
Texas          97654321
New York    12341234124
Florida       987987987

   a  b
0  0  0
1  1  2
2  2  4

   a    b     c
0  1  2.0   NaN
1  3  NaN  14.0

In [8]:
# From a dictionary of Series objects
x = pd.DataFrame({'population': population, 'area': area})
display(x)

# From a two-dimensional Numpy array
x = pd.DataFrame(
    np.random.rand(3, 2),
    columns=['foo', 'bar'],
    index=['a','b','c'],
)
display(x)

             population    area
California    123456789  123123
Florida       987987987  123456
New York    12341234124   98765
Texas          97654321   98098

        foo       bar
a  0.395733  0.527467
b  0.830723  0.238167
c  0.435502  0.928418

### Index Object
Can be seen as an inmutable array or a multiset (thus its supports intersection and union operations)

In [10]:
ind = pd.Index([2, 3, 5, 7, 11])
display(ind)

# Operates like an array
display(ind[1])
display(ind[0:2])
print(ind.size, ind.shape, ind.ndim, ind.dtype)

# They are inmutable
ind[0] = 4

Index([2, 3, 5, 7, 11], dtype='int64')

np.int64(3)

Index([2, 3], dtype='int64')

5 (5,) 1 int64

TypeError: Index does not support mutable operations

## Indexing and Selection

In [11]:
data = pd.Series([0.25, 0.5, 0.75, 1.0], index=['a', 'b', 'c', 'd'])
display(data)

display(data['b'])

# Like Python dictionaries
display(data.keys())
display(list(data.items()))
data['e'] = 0.8

# Fancy indexing
display(data[['a', 'e']])

# masking
display(data[(data > 0.3) & (data < 0.8)])

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

np.float64(0.5)

Index(['a', 'b', 'c', 'd'], dtype='object')

[('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)]

a    0.25
e    0.80
dtype: float64

b    0.50
c    0.75
dtype: float64

In [12]:
data = pd.Series(['a', 'b', 'c'], index=[1, 3, 5])
display(data)

# Explicit index at indexing
display(data[1])

# Implicit index at slicing
display(data[1:3])

1    a
3    b
5    c
dtype: object

'a'

3    b
5    c
dtype: object

In [13]:
# We shall use `loc` and `iloc` methods:
# loc usses the explicit indexes
display(data.loc[1])
display(data.loc[1:3])

# iloc uses the implicit indexes
display(data.iloc[1])
display(data.iloc[1:3])

'a'

1    a
3    b
dtype: object

'b'

3    b
5    c
dtype: object

In [14]:
data = pd.DataFrame({'area': area, 'pop': population})
display(data)

# We can add a new column
data['density'] = data['pop'] / data['area']
display(data)

# We can access the values of the DataFrame as a two-dimensional numpy array
display(data.values)

              area          pop
California  123123    123456789
Florida     123456    987987987
New York     98765  12341234124
Texas        98098     97654321

              area          pop        density
California  123123    123456789    1002.711021
Florida     123456    987987987    8002.753912
New York     98765  12341234124  124955.542186
Texas        98098     97654321     995.477186

array([[1.23123000e+05, 1.23456789e+08, 1.00271102e+03],
       [1.23456000e+05, 9.87987987e+08, 8.00275391e+03],
       [9.87650000e+04, 1.23412341e+10, 1.24955542e+05],
       [9.80980000e+04, 9.76543210e+07, 9.95477186e+02]])

In [15]:
# loc and iloc can be used too
display(data.loc[:'New York', :'pop'])
display(data.iloc[:3, :2])

              area          pop
California  123123    123456789
Florida     123456    987987987
New York     98765  12341234124

              area          pop
California  123123    123456789
Florida     123456    987987987
New York     98765  12341234124

## Operating on Data
Any numpy's ufunc will work on a pandas Series or DataFrame object

In [16]:
# When some data is NaN and we do an operation it will be NaN:
area2 = pd.Series({'Alaska': 1234, 'Texas': 9866, 'New York': 4567})
pop2 = pd.Series({'California': 987, 'Texas': 123, 'New York': 444})
display(area2 / pop2)

# Similarly:
A = pd.Series([2, 4, 6], index=[0, 1, 2])
B = pd.Series([1, 3, 5], index=[1, 2, 3])
display(A + B)

Alaska              NaN
California          NaN
New York      10.286036
Texas         80.211382
dtype: float64

0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

In [17]:
# We can specify the parameter fill_value to fill out all the NaNs values:
display(A.add(B, fill_value=0))

0    2.0
1    5.0
2    9.0
3    5.0
dtype: float64

## Handling Missing Data
Pandas has `None` and `NaN` as special centinels. The first one is an object and the second one is a floating numeric value

In [18]:
display(data.isnull()) # Boolean mask indicating missing values
display(data.notnull()) # Opposite of the above
display(data.dropna()) # Filtered version of the data
display(data.fillna(0)) # Returns a copy with missing values inmputed

             area    pop  density
California  False  False    False
Florida     False  False    False
New York    False  False    False
Texas       False  False    False

            area   pop  density
California  True  True     True
Florida     True  True     True
New York    True  True     True
Texas       True  True     True

              area          pop        density
California  123123    123456789    1002.711021
Florida     123456    987987987    8002.753912
New York     98765  12341234124  124955.542186
Texas        98098     97654321     995.477186

              area          pop        density
California  123123    123456789    1002.711021
Florida     123456    987987987    8002.753912
New York     98765  12341234124  124955.542186
Texas        98098     97654321     995.477186

## Aggregation

In [19]:
# We'll work with the planets dataset
import seaborn as sns
planets = sns.load_dataset('planets')
display(planets.shape)
display(planets.head())

(1035, 6)

            method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

In pandas the aggregates returns by default the result on each column

In [20]:
planets_num = planets.select_dtypes(include='number')
display(planets_num.head())

display(planets_num.mean())

# We can use the axis argument to change its behaviour
display(planets_num.mean(axis='columns').head())

   number  orbital_period   mass  distance  year
0       1         269.300   7.10     77.40  2006
1       1         874.774   2.21     56.95  2008
2       1         763.000   2.60     19.84  2011
3       1         326.030  19.40    110.62  2007
4       1         516.220  10.50    119.47  2009

number               1.785507
orbital_period    2002.917596
mass                 2.638161
distance           264.069282
year              2009.070531
dtype: float64

0    472.1600
1    588.5868
2    559.4880
3    492.8100
4    531.2380
dtype: float64

In [21]:
# The describe method executes some aggreation functions above all the dataset
display(planets.dropna().describe())

          number  orbital_period        mass    distance         year
count  498.00000      498.000000  498.000000  498.000000   498.000000
mean     1.73494      835.778671    2.509320   52.068213  2007.377510
std      1.17572     1469.128259    3.636274   46.596041     4.167284
min      1.00000        1.328300    0.003600    1.350000  1989.000000
25%      1.00000       38.272250    0.212500   24.497500  2005.000000
50%      1.00000      357.000000    1.245000   39.940000  2009.000000
75%      2.00000      999.600000    2.867500   59.332500  2011.000000
max      6.00000    17337.500000   25.000000  354.000000  2014.000000

## Exercises

In [22]:
import numpy as np
import pandas as pd
import seaborn as sns

planets = sns.load_dataset('planets')

In [23]:
# 1.- Show the first 10 rows of a dataset
planets.head(10)

            method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009
5  Radial Velocity       1         185.840   4.80     76.39  2008
6  Radial Velocity       1        1773.400   4.64     18.15  2002
7  Radial Velocity       1         798.500    NaN     21.41  1996
8  Radial Velocity       1         993.300  10.30     73.10  2008
9  Radial Velocity       2         452.800   1.99     74.79  2010

In [24]:
# 2.- From a dataset get:
# - Number of rows and columns
# - Name of the columns
# - Data types
# - Statistics

display(planets.shape)
display(planets.columns)
display(planets.dtypes)
display(planets.dropna().describe())

(1035, 6)

Index(['method', 'number', 'orbital_period', 'mass', 'distance', 'year'], dtype='object')

method             object
number              int64
orbital_period    float64
mass              float64
distance          float64
year                int64
dtype: object

          number  orbital_period        mass    distance         year
count  498.00000      498.000000  498.000000  498.000000   498.000000
mean     1.73494      835.778671    2.509320   52.068213  2007.377510
std      1.17572     1469.128259    3.636274   46.596041     4.167284
min      1.00000        1.328300    0.003600    1.350000  1989.000000
25%      1.00000       38.272250    0.212500   24.497500  2005.000000
50%      1.00000      357.000000    1.245000   39.940000  2009.000000
75%      2.00000      999.600000    2.867500   59.332500  2011.000000
max      6.00000    17337.500000   25.000000  354.000000  2014.000000

In [25]:
# 3.- Select some columns.
display(planets['number'].head())
display(planets['orbital_period'].head())

# 4.- Select the columns with indexes between 20 and 30
display(planets.iloc[20:31])

0    1
1    1
2    1
3    1
4    1
Name: number, dtype: int64

0    269.300
1    874.774
2    763.000
3    326.030
4    516.220
Name: orbital_period, dtype: float64

             method  number  orbital_period   mass  distance  year
20  Radial Velocity       5         0.73654    NaN     12.53  2011
21  Radial Velocity       5       261.20000  0.172     12.53  2007
22  Radial Velocity       3         4.21500  0.016      8.52  2009
23  Radial Velocity       3        38.02100  0.057      8.52  2009
24  Radial Velocity       3       123.01000  0.072      8.52  2009
25  Radial Velocity       1       116.68840    NaN     18.11  1996
26  Radial Velocity       1       691.90000    NaN     81.50  2012
27  Radial Velocity       1       952.70000  5.300     97.18  2008
28  Radial Velocity       1       181.40000  3.200     45.52  2013
29          Imaging       1             NaN    NaN     45.52  2005
30          Imaging       1             NaN    NaN    165.00  2007

In [26]:
# 5.- Select all the planets discovered after 2010
display(planets[planets['year'] >= 2010])

# 6.- Select all the planets discovered after 2010 with a non-NaN mass with a distance greater than 100
display(planets.dropna()[(planets['year'] >= 2010) & (planets['distance'] > 100)])

               method  number  orbital_period  mass  distance  year
2     Radial Velocity       1      763.000000  2.60     19.84  2011
9     Radial Velocity       2      452.800000  1.99     74.79  2010
10    Radial Velocity       2      883.000000  0.86     74.79  2010
20    Radial Velocity       5        0.736540   NaN     12.53  2011
26    Radial Velocity       1      691.900000   NaN     81.50  2012
...               ...     ...             ...   ...       ...   ...
1025          Transit       1        3.067850   NaN     60.00  2012
1026          Transit       1        0.925542   NaN    470.00  2014
1027          Imaging       1             NaN   NaN     19.20  2011
1028          Transit       1        3.352057   NaN   3200.00  2012
1029          Imaging       1             NaN   NaN     10.10  2012

[597 rows x 6 columns]

/tmp/ipykernel_87348/255122509.py:5: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  display(planets.dropna()[(planets['year'] >= 2010) & (planets['distance'] > 100)])

              method  number  orbital_period    mass  distance  year
84   Radial Velocity       1       137.48000   1.110    175.44  2013
181  Radial Velocity       2      1022.00000   3.400    354.00  2011
202  Radial Velocity       1       431.80000   3.100    167.50  2011
206  Radial Velocity       1       311.60000   1.600    115.21  2013
218  Radial Velocity       1       177.11000   7.600    150.60  2011
257  Radial Velocity       1       772.00000   2.700    127.88  2011
282  Radial Velocity       1       387.10000   1.700    168.92  2011
285  Radial Velocity       1       912.00000   1.800    121.07  2011
290  Radial Velocity       1       326.60000   1.300    136.80  2011
376  Radial Velocity       1       705.00000   1.300    112.23  2011
394  Radial Velocity       1       361.10000   0.900    132.80  2011
396  Radial Velocity       1       647.30000   4.000    221.24  2011
400  Radial Velocity       1       436.90000   1.800    150.38  2011
405  Radial Velocity       1       868.00000   1.400    130.89  2011
406  Radial Velocity       1       157.57000   1.700    140.85  2011
414  Radial Velocity       1       778.10000   5.900    138.50  2011
415  Radial Velocity       1         6.49500   0.960    121.07  2010
426  Radial Velocity       1       443.40000   2.600    138.50  2011
444  Radial Velocity       1       670.00000   2.100    110.62  2011
461  Radial Velocity       1       883.00000   2.200    121.36  2011
480  Radial Velocity       1      1299.00000   1.900    106.38  2011
483  Radial Velocity       1       176.30000   2.900    126.10  2010
495  Radial Velocity       1       689.00000   1.500    182.82  2011
509  Radial Velocity       1       521.00000   1.800    114.15  2011
587  Radial Velocity       1       875.50000   9.900    352.11  2012
610  Radial Velocity       1       672.10000  11.100    289.02  2012
620  Radial Velocity       1       745.70000   5.300    307.69  2011
627  Radial Velocity       1        16.20000   1.250    223.21  2010
636  Radial Velocity       1       124.60000   9.180    149.25  2013
649          Transit       1         2.70339   1.470    178.00  2013
784  Radial Velocity       3       580.00000   0.947    135.00  2012

In [27]:
# 7.- Count the number of null values on a column
planets.isnull().sum()

method              0
number              0
orbital_period     43
mass              522
distance          227
year                0
dtype: int64

In [28]:
# 8.- Remove the rows with some null value
display(planets.dropna().head())

# 9.- Fill up the null values of distance column by its mean
planets['distance'] = planets['distance'].fillna(planets['distance'].mean())
display(planets.head())

            method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

            method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

In [29]:
# 10.- Get all categories from the method's column
display(pd.unique(planets['method']))

# 11.- Generate a new column
planets['O/D'] = planets['orbital_period'] / planets['distance']
display(planets.head())

array(['Radial Velocity', 'Imaging', 'Eclipse Timing Variations',
       'Transit', 'Astrometry', 'Transit Timing Variations',
       'Orbital Brightness Modulation', 'Microlensing', 'Pulsar Timing',
       'Pulsation Timing Variations'], dtype=object)

            method  number  orbital_period   mass  distance  year        O/D
0  Radial Velocity       1         269.300   7.10     77.40  2006   3.479328
1  Radial Velocity       1         874.774   2.21     56.95  2008  15.360386
2  Radial Velocity       1         763.000   2.60     19.84  2011  38.457661
3  Radial Velocity       1         326.030  19.40    110.62  2007   2.947297
4  Radial Velocity       1         516.220  10.50    119.47  2009   4.320917

In [30]:
# 12.- Rename some column
planets = planets.rename(columns={'O/D': 'Orb/Dist'})
display(planets.head())

# 13.- Drop a column
planets = planets.drop(columns='Orb/Dist')
display(planets.head())

            method  number  orbital_period   mass  distance  year   Orb/Dist
0  Radial Velocity       1         269.300   7.10     77.40  2006   3.479328
1  Radial Velocity       1         874.774   2.21     56.95  2008  15.360386
2  Radial Velocity       1         763.000   2.60     19.84  2011  38.457661
3  Radial Velocity       1         326.030  19.40    110.62  2007   2.947297
4  Radial Velocity       1         516.220  10.50    119.47  2009   4.320917

            method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

In [31]:
# 14.- Sorts the dataframe by the year
planets = planets.sort_values(by='year')
display(planets.head())

              method  number  orbital_period    mass    distance  year
441  Radial Velocity       1       83.888000  11.680   40.570000  1989
942    Pulsar Timing       3       66.541900     NaN  264.069282  1992
941    Pulsar Timing       3       25.262000     NaN  264.069282  1992
943    Pulsar Timing       3       98.211400     NaN  264.069282  1994
16   Radial Velocity       1        4.230785   0.472   15.360000  1995

In [32]:
# 15.- Transform the column year xxxx into 'x.xxx'
planets['year'] = planets['year'].map(lambda x: f'{x:,}'.replace(',', '.'))
display(planets.head())

              method  number  orbital_period    mass    distance   year
441  Radial Velocity       1       83.888000  11.680   40.570000  1.989
942    Pulsar Timing       3       66.541900     NaN  264.069282  1.992
941    Pulsar Timing       3       25.262000     NaN  264.069282  1.992
943    Pulsar Timing       3       98.211400     NaN  264.069282  1.994
16   Radial Velocity       1        4.230785   0.472   15.360000  1.995

In [33]:
# 16.- Compute the average distance by year
display(planets.groupby('year')['distance'].mean())

year
1.989     40.570000
1.992    264.069282
1.994    264.069282
1.995     15.360000
1.996     15.866667
1.997     17.430000
1.998     26.302000
1.999     30.947333
2.000     30.752500
2.001     36.531667
2.002     51.260915
2.003     51.924771
2.004    193.926840
2.005     57.642527
2.006    621.890898
2.007    177.963665
2.008    121.030173
2.009    109.915808
2.010    257.438074
2.011    310.104911
2.012    458.560249
2.013    423.938697
2.014    275.119365
Name: distance, dtype: float64

In [34]:
# 17.- For each method compute: the maximum distance, the number of discovers and the medium mass
planets['distance'] = planets['distance'].fillna(planets['distance'].mean())
planets['mass'] = planets['mass'].fillna(planets['mass'].mean())
display(planets.groupby('method').agg({
    'distance': 'max',
    'method': 'count',
    'mass': 'mean',
}))

                                  distance  method      mass
method
Astrometry                       20.770000       2  2.638161
Eclipse Timing Variations       500.000000       9  3.190792
Imaging                         264.069282      38  2.638161
Microlensing                   7720.000000      23  2.638161
Orbital Brightness Modulation  1180.000000       3  2.638161
Pulsar Timing                  1200.000000       5  2.638161
Pulsation Timing Variations     264.069282       1  2.638161
Radial Velocity                 354.000000     553  2.631279
Transit                        8500.000000     397  2.635218
Transit Timing Variations      2119.000000       4  2.638161

In [35]:
# 18.- Build two DataFrames: The df without the mass and a numpy's array with the mass
y = planets['mass']
display(y.head())

X = planets.drop(columns='mass')
display(X.head())

display(planets.head())

# 19.- Transform year into numeric and remove from X the non-numeric columns
X['year'] = X['year'].map(lambda x: int(x[0] + x[2:]))
X = X.select_dtypes(include='number')
display(X.head())

441    11.680000
942     2.638161
941     2.638161
943     2.638161
16      0.472000
Name: mass, dtype: float64

              method  number  orbital_period    distance   year
441  Radial Velocity       1       83.888000   40.570000  1.989
942    Pulsar Timing       3       66.541900  264.069282  1.992
941    Pulsar Timing       3       25.262000  264.069282  1.992
943    Pulsar Timing       3       98.211400  264.069282  1.994
16   Radial Velocity       1        4.230785   15.360000  1.995

              method  number  orbital_period       mass    distance   year
441  Radial Velocity       1       83.888000  11.680000   40.570000  1.989
942    Pulsar Timing       3       66.541900   2.638161  264.069282  1.992
941    Pulsar Timing       3       25.262000   2.638161  264.069282  1.992
943    Pulsar Timing       3       98.211400   2.638161  264.069282  1.994
16   Radial Velocity       1        4.230785   0.472000   15.360000  1.995

     number  orbital_period    distance  year
441       1       83.888000   40.570000  1989
942       3       66.541900  264.069282  1992
941       3       25.262000  264.069282  1992
943       3       98.211400  264.069282  1994
16        1        4.230785   15.360000  1995

In [36]:
# 20.- One-Hot Encode a column 
display(X.head())

X = pd.get_dummies(X, columns=['number'])
display(X.head())

     number  orbital_period    distance  year
441       1       83.888000   40.570000  1989
942       3       66.541900  264.069282  1992
941       3       25.262000  264.069282  1992
943       3       98.211400  264.069282  1994
16        1        4.230785   15.360000  1995

,orbital_period,distance,year,number_1,number_2,number_3,number_4,number_5,number_6,number_7
441,83.888000,40.570000,1989,True,False,False,False,False,False,False
942,66.541900,264.069282,1992,False,False,True,False,False,False,False
941,25.262000,264.069282,1992,False,False,True,False,False,False,False
943,98.211400,264.069282,1994,False,False,True,False,False,False,False
16,4.230785,15.360000,1995,True,False,False,False,False,False,False

In [37]:
# 21.- Show and remove the duplicated rows
dupl = planets[planets.duplicated(keep=False)]
print(f'There are {len(dupl)} duplicated rows:')
display(dupl)

display(planets.shape)
planets = planets.drop_duplicates()
print('Duplicated lines removed')
display(planets.shape)

There are 8 duplicated rows:

           method  number  orbital_period      mass     distance   year
957       Imaging       1             NaN  2.638161   264.069282  2.008
902  Microlensing       1             NaN  2.638161   264.069282  2.008
903  Microlensing       1             NaN  2.638161   264.069282  2.008
33        Imaging       1             NaN  2.638161   264.069282  2.008
923  Microlensing       1             NaN  2.638161   264.069282  2.009
904  Microlensing       1             NaN  2.638161   264.069282  2.009
925  Microlensing       2             NaN  2.638161  4080.000000  2.012
926  Microlensing       2             NaN  2.638161  4080.000000  2.012

(1035, 6)

Duplicated lines removed

(1031, 6)

In [38]:
# 22.- Return the 10th more furthest planets
display(planets.nlargest(10, 'distance'))

            method  number  orbital_period      mass  distance   year
951        Transit       1        4.200000  2.638161    8500.0  2.006
952        Transit       1        1.796000  2.638161    8500.0  2.006
911   Microlensing       1             NaN  2.638161    7720.0  2.012
912   Microlensing       1             NaN  2.638161    7560.0  2.013
928   Microlensing       1             NaN  2.638161    4970.0  2.013
925   Microlensing       2             NaN  2.638161    4080.0  2.012
905   Microlensing       1             NaN  2.638161    3600.0  2.013
1028       Transit       1        3.352057  2.638161    3200.0  2.012
910   Microlensing       1             NaN  2.638161    2800.0  2.012
727        Transit       1        6.873490  2.638161    2700.0  2.010

In [41]:
# 23.- Change the dtype of a column
display(planets.dtypes)

planets['year'] = planets['year'].astype(float)
display(planets.head())
display(planets.dtypes)

method             object
number              int64
orbital_period    float64
mass              float64
distance          float64
year               object
dtype: object

              method  number  orbital_period       mass    distance   year
441  Radial Velocity       1       83.888000  11.680000   40.570000  1.989
942    Pulsar Timing       3       66.541900   2.638161  264.069282  1.992
941    Pulsar Timing       3       25.262000   2.638161  264.069282  1.992
943    Pulsar Timing       3       98.211400   2.638161  264.069282  1.994
16   Radial Velocity       1        4.230785   0.472000   15.360000  1.995

method             object
number              int64
orbital_period    float64
mass              float64
distance          float64
year              float64
dtype: object